name: Python Application CI

on:
  push:
    branches:
      - master
      - dashboard-design
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Lint with Flake8
      - name: Lint with Flake8
        run: |
          pip install flake8
          flake8 . --count --max-complexity=10 --max-line-length=127 --statistics

      # Step 5: Format check with Black
      - name: Format check with Black
        run: |
          pip install black
          black --check .

      # Step 6: Run tests
      # - name: Run tests
      #   run: |
      #     pip install pytest
      #     pytest
